import { VFSFile } from "@/hooks/v2/useVFS";

export interface Template {
  id: string;
  title: string;
  description: string;
  category: TemplateCategory;
  icon: string;
  colors: { primary: string; secondary: string; accent: string };
  files: VFSFile[];
  pageCount: number;
  featured: boolean;
  prompt: string;
}

export type TemplateCategory =
  | "restaurant" | "health" | "real-estate" | "ecommerce"
  | "legal" | "beauty" | "fitness" | "tech"
  | "education" | "photography" | "consulting" | "portfolio";

export const CATEGORY_LABELS: Record<TemplateCategory, { label: string; icon: string }> = {
  restaurant: { label: "مطاعم وكافيهات", icon: "🍽️" },
  health: { label: "صحة وطب", icon: "🏥" },
  "real-estate": { label: "عقارات وبناء", icon: "🏢" },
  ecommerce: { label: "تجارة إلكترونية", icon: "🛒" },
  legal: { label: "قانون واستشارات", icon: "⚖️" },
  beauty: { label: "جمال وعناية", icon: "✂️" },
  fitness: { label: "رياضة ولياقة", icon: "💪" },
  tech: { label: "تقنية وبرمجة", icon: "💻" },
  education: { label: "تعليم وتدريب", icon: "🎓" },
  photography: { label: "فنون وتصوير", icon: "📸" },
  consulting: { label: "استشارات", icon: "💼" },
  portfolio: { label: "مواقع شخصية", icon: "🧑‍💻" },
};

// Helper to create minimal VFS files for each template
function makeFiles(componentNames: string[], cssVars: string): VFSFile[] {
  const files: VFSFile[] = [
    { name: "styles.css", content: cssVars, language: "css" },
  ];
  componentNames.forEach((name) => {
    files.push({
      name: `${name}.tsx`,
      content: `// ${name} component - will be generated by AI`,
      language: "tsx",
    });
  });
  return files;
}

export const TEMPLATES: Template[] = [
  {
    id: "restaurant-luxury",
    title: "مطعم فاخر",
    description: "موقع أنيق لمطعم راقٍ مع قائمة طعام تفاعلية، نظام حجوزات، معرض صور الأطباق، وقسم آراء الزوار.",
    category: "restaurant",
    icon: "🍽️",
    colors: { primary: "#D4A574", secondary: "#2C1810", accent: "#E8C07D" },
    files: makeFiles(["App", "Header", "Hero", "Menu", "Reservations", "Gallery", "Testimonials", "Footer"], `:root { --primary: #D4A574; --secondary: #2C1810; --accent: #E8C07D; }`),
    pageCount: 8,
    featured: true,
    prompt: "أبي موقع لمطعم سعودي فاخر مع قائمة طعام تفاعلية تعرض الأطباق مع الأسعار والصور، نظام حجز طاولات، معرض صور للأجواء والأطباق، قسم آراء الزوار، معلومات التواصل والموقع على الخريطة. التصميم يكون فخم وأنيق بألوان ذهبية ودافئة.",
  },
  {
    id: "medical-clinic",
    title: "عيادة طبية",
    description: "موقع احترافي لعيادة طبية مع خدمات العيادة، فريق الأطباء، نظام مواعيد، وتفاصيل التأمين الصحي.",
    category: "health",
    icon: "🏥",
    colors: { primary: "#10B981", secondary: "#1E293B", accent: "#34D399" },
    files: makeFiles(["App", "Header", "Hero", "Services", "Doctors", "Appointments", "Insurance", "Contact", "Footer"], `:root { --primary: #10B981; --secondary: #1E293B; --accent: #34D399; }`),
    pageCount: 9,
    featured: true,
    prompt: "أبي موقع لعيادة طبية متخصصة مع صفحة خدمات العيادة (أسنان، جلدية، عيون)، قسم فريق الأطباء مع صورهم وتخصصاتهم، نظام حجز مواعيد، قسم التأمينات الصحية المقبولة، أسئلة شائعة، ومعلومات التواصل. التصميم نظيف وطبي بألوان خضراء مريحة.",
  },
  {
    id: "real-estate-agency",
    title: "شركة عقارات",
    description: "موقع عقاري متكامل مع معرض العقارات المتاحة، فلاتر بحث متقدمة، تفاصيل كل عقار، وطلب معاينة.",
    category: "real-estate",
    icon: "🏢",
    colors: { primary: "#0EA5E9", secondary: "#1E293B", accent: "#38BDF8" },
    files: makeFiles(["App", "Header", "Hero", "Properties", "PropertyCard", "Search", "Services", "About", "Contact", "Footer"], `:root { --primary: #0EA5E9; --secondary: #1E293B; --accent: #38BDF8; }`),
    pageCount: 10,
    featured: false,
    prompt: "أبي موقع لشركة عقارات سعودية مع معرض عقارات يعرض الفلل والشقق والأراضي مع الصور والأسعار والمواقع، فلاتر بحث (نوع العقار، المدينة، السعر)، صفحة تفاصيل لكل عقار، نموذج طلب معاينة، خدمات الشركة (بيع، شراء، إيجار، تقييم)، وقسم عن الشركة.",
  },
  {
    id: "ecommerce-store",
    title: "متجر إلكتروني",
    description: "متجر إلكتروني عصري مع عرض المنتجات، سلة المشتريات، فئات المنتجات، وعروض خاصة.",
    category: "ecommerce",
    icon: "🛒",
    colors: { primary: "#8B5CF6", secondary: "#1E1B2E", accent: "#A78BFA" },
    files: makeFiles(["App", "Header", "Hero", "FeaturedProducts", "ProductCard", "Categories", "Offers", "Newsletter", "Footer"], `:root { --primary: #8B5CF6; --secondary: #1E1B2E; --accent: #A78BFA; }`),
    pageCount: 9,
    featured: true,
    prompt: "أبي متجر إلكتروني احترافي لبيع الإلكترونيات مع عرض المنتجات في شبكة جميلة مع الصور والأسعار، فئات المنتجات (هواتف، لابتوبات، اكسسوارات)، قسم عروض خاصة، بانر إعلاني متحرك، سلة مشتريات، قسم اشتراك بالنشرة البريدية. التصميم عصري بألوان بنفسجية.",
  },
  {
    id: "law-firm",
    title: "مكتب محاماة",
    description: "موقع احترافي لمكتب محاماة مع مجالات الممارسة، فريق المحامين، قصص نجاح، واستشارة مجانية.",
    category: "legal",
    icon: "⚖️",
    colors: { primary: "#1E3A5F", secondary: "#0F172A", accent: "#C4A35A" },
    files: makeFiles(["App", "Header", "Hero", "PracticeAreas", "Team", "CaseStudies", "Consultation", "Contact", "Footer"], `:root { --primary: #1E3A5F; --secondary: #0F172A; --accent: #C4A35A; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لمكتب محاماة واستشارات قانونية مع مجالات الممارسة (قانون تجاري، عقاري، أسري، جنائي)، فريق المحامين مع خبراتهم وشهاداتهم، قصص نجاح وإحصائيات، نموذج طلب استشارة مجانية، ومعلومات التواصل. التصميم رسمي وموثوق بألوان كحلية وذهبية.",
  },
  {
    id: "beauty-salon",
    title: "صالون تجميل",
    description: "موقع أنيق لصالون تجميل مع الخدمات والأسعار، معرض الأعمال، حجز مواعيد، وعروض موسمية.",
    category: "beauty",
    icon: "✂️",
    colors: { primary: "#EC4899", secondary: "#1F1F1F", accent: "#F9A8D4" },
    files: makeFiles(["App", "Header", "Hero", "Services", "Gallery", "Booking", "Offers", "Testimonials", "Footer"], `:root { --primary: #EC4899; --secondary: #1F1F1F; --accent: #F9A8D4; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لصالون تجميل نسائي فاخر مع قائمة الخدمات (قص شعر، صبغة، مكياج، عناية بالبشرة) مع الأسعار، معرض صور الأعمال السابقة، نظام حجز مواعيد، عروض موسمية، آراء العميلات. التصميم أنثوي وأنيق بألوان وردية.",
  },
  {
    id: "gym-fitness",
    title: "نادي رياضي",
    description: "موقع ديناميكي لنادي رياضي مع الباقات والأسعار، جدول الحصص، فريق المدربين، ومعرض الصور.",
    category: "fitness",
    icon: "💪",
    colors: { primary: "#EF4444", secondary: "#111111", accent: "#F97316" },
    files: makeFiles(["App", "Header", "Hero", "Plans", "Schedule", "Trainers", "Gallery", "CTA", "Footer"], `:root { --primary: #EF4444; --secondary: #111111; --accent: #F97316; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لنادي رياضي وجيم مع باقات الاشتراك (شهري، ربع سنوي، سنوي) مع الأسعار والمميزات، جدول الحصص الأسبوعي (يوغا، كروس فت، ملاكمة)، فريق المدربين مع صورهم وتخصصاتهم، معرض صور النادي، زر تسجيل الآن. التصميم قوي وحماسي بألوان حمراء وبرتقالية.",
  },
  {
    id: "tech-company",
    title: "شركة برمجيات",
    description: "موقع عصري لشركة تقنية مع الخدمات والحلول، فريق العمل، مشاريع سابقة، ومدونة تقنية.",
    category: "tech",
    icon: "💻",
    colors: { primary: "#3B82F6", secondary: "#0F172A", accent: "#06B6D4" },
    files: makeFiles(["App", "Header", "Hero", "Services", "Portfolio", "Team", "Blog", "Contact", "Footer"], `:root { --primary: #3B82F6; --secondary: #0F172A; --accent: #06B6D4; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لشركة برمجيات وتقنية مع خدمات الشركة (تطوير تطبيقات، مواقع، أنظمة، ذكاء اصطناعي)، معرض المشاريع السابقة مع الوصف والتقنيات المستخدمة، فريق العمل، قسم مدونة تقنية، نموذج طلب عرض سعر. التصميم عصري وتقني بألوان زرقاء وسيان.",
  },
  {
    id: "education-academy",
    title: "أكاديمية تعليمية",
    description: "موقع تعليمي متكامل مع الدورات المتاحة، فريق المدرسين، شهادات الطلاب، ونظام تسجيل.",
    category: "education",
    icon: "🎓",
    colors: { primary: "#7C3AED", secondary: "#1E1B4B", accent: "#A78BFA" },
    files: makeFiles(["App", "Header", "Hero", "Courses", "CourseCard", "Instructors", "Testimonials", "Registration", "Footer"], `:root { --primary: #7C3AED; --secondary: #1E1B4B; --accent: #A78BFA; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لأكاديمية تعليمية مع الدورات المتاحة (برمجة، تصميم، تسويق، لغات) مع الوصف والمدة والسعر، فريق المدرسين مع خبراتهم، شهادات وآراء الطلاب السابقين، نموذج تسجيل في الدورات، إحصائيات (عدد الطلاب، الدورات، سنوات الخبرة). التصميم تعليمي بألوان بنفسجية.",
  },
  {
    id: "photography-portfolio",
    title: "مصور فوتوغرافي",
    description: "بورتفوليو أنيق لمصور مع معرض صور مقسم بالفئات، خدمات التصوير، الأسعار، ونموذج حجز.",
    category: "photography",
    icon: "📸",
    colors: { primary: "#F59E0B", secondary: "#18181B", accent: "#FBBF24" },
    files: makeFiles(["App", "Header", "Hero", "Gallery", "Services", "Pricing", "About", "Booking", "Footer"], `:root { --primary: #F59E0B; --secondary: #18181B; --accent: #FBBF24; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع بورتفوليو لمصور فوتوغرافي مع معرض صور مقسم بالفئات (حفلات زفاف، بورتريه، منتجات، مناظر طبيعية)، خدمات التصوير مع الأسعار، قسم عن المصور مع خبرته، نموذج حجز جلسة تصوير. التصميم فني وأنيق بألوان ذهبية على خلفية داكنة.",
  },
  {
    id: "consulting-firm",
    title: "شركة استشارات",
    description: "موقع احترافي لشركة استشارية مع مجالات الخبرة، فريق المستشارين، دراسات حالة، وطلب استشارة.",
    category: "consulting",
    icon: "💼",
    colors: { primary: "#0D9488", secondary: "#0F172A", accent: "#2DD4BF" },
    files: makeFiles(["App", "Header", "Hero", "Expertise", "Team", "CaseStudies", "Process", "Contact", "Footer"], `:root { --primary: #0D9488; --secondary: #0F172A; --accent: #2DD4BF; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع لشركة استشارات إدارية ومالية مع مجالات الخبرة (استشارات مالية، إدارية، تقنية، موارد بشرية)، فريق المستشارين مع مؤهلاتهم، دراسات حالة ومشاريع ناجحة، منهجية العمل (4 خطوات)، نموذج طلب استشارة. التصميم رسمي ومهني بألوان فيروزية.",
  },
  {
    id: "personal-portfolio",
    title: "موقع شخصي",
    description: "بورتفوليو شخصي احترافي مع نبذة تعريفية، المهارات، المشاريع السابقة، والسيرة الذاتية القابلة للتحميل.",
    category: "portfolio",
    icon: "🧑‍💻",
    colors: { primary: "#6366F1", secondary: "#0F0F1A", accent: "#818CF8" },
    files: makeFiles(["App", "Header", "Hero", "About", "Skills", "Projects", "Experience", "Contact", "Footer"], `:root { --primary: #6366F1; --secondary: #0F0F1A; --accent: #818CF8; }`),
    pageCount: 9,
    featured: false,
    prompt: "أبي موقع بورتفوليو شخصي احترافي مع نبذة تعريفية (الاسم، التخصص، نبذة قصيرة)، قسم المهارات (frontend، backend، أدوات) مع progress bars، معرض المشاريع السابقة مع الروابط والوصف، الخبرات العملية، نموذج تواصل، روابط السوشال ميديا. التصميم عصري بألوان نيلية على خلفية داكنة.",
  },
];

export function getTemplatesByCategory(category: TemplateCategory): Template[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export function getFeaturedTemplates(): Template[] {
  return TEMPLATES.filter((t) => t.featured);
}

export function searchTemplates(query: string): Template[] {
  const q = query.toLowerCase();
  return TEMPLATES.filter(
    (t) => t.title.toLowerCase().includes(q) || t.description.toLowerCase().includes(q)
  );
}
